### ISSUE TITLE
Application doesn't display properly when running on a Mac

### ISSUE THREAD

**Issue by danysdragons** [roslynpad/roslynpad#248]
Application initially appeared to be entirely non-functional, opening with a black canvas. 

I was able to get the application to function by dragging the corner to resize, then toggling between a normal window and fullscreen a couple of times. I then had an editor that was basically usable - I was able to write and execute code, Intellisense was working - but there were still places where the window wasn't being rendered quite right - see attached screenshot for an example.

MacOS Mojave 10.14.3 (Latest at time of issue creation)
.NET Core 2.2.105

![RoslynPad_1](https://user-images.githubusercontent.com/40280395/54563565-e1e4b280-499f-11e9-82a7-e6eecc0d9bc3.png)

**Comment by aelij** [comment]
> places where the window wasn't being rendered quite right

Could you point me to those? Note that the cross-platform version is an Avalonia-based rewrite of the entire UI, so it's not quite as polished as the WPF version :)

**Comment by aelij** [comment]
See https://github.com/AvaloniaUI/Avalonia/issues/2363
Seems like it was fixed but not yet published. We'll have to wait for a newer version

**Comment by mustakimali** [comment]
Hello @aelij - was that bugfix released with v0.8.2
https://github.com/AvaloniaUI/Avalonia/releases/tag/0.8.2

It would be great if you could update Roslynpad.

**Comment by giuliano-barberi-tf** [comment]
It looks like it's been updated to 0.8.3 but as far as I can tell it's still not rendering correctly. Does anyone know what the issue is? I don't mind looking into it

**Comment by aelij** [comment]
@giuliano-barberi-tf As I said, I haven't invested time in polishing the Avalonia version, so if you're up to it I'd really appreciate it.

**Comment by SittenSpynne** [comment]
Still active, I just decided to try it out today.

**Comment by aelij** [comment]
This should be fixed in the latest Avalonia
