### ISSUE TITLE
can't launch app on Linux

### ISSUE THREAD

**Issue by catalin560** [roslynpad/roslynpad#499]
**Describe the bug**
```
☁  RoslynPadAvalonia  dotnet RoslynPad.dll                                   
Unhandled exception. System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at RoslynPad.UI.OpenDocumentViewModel.set_Platform(ExecutionPlatform value) in D:\src\gh\aelij\roslynpad\src\RoslynPad.Common.UI\ViewModels\OpenDocumentViewModel.cs:line 453
   at RoslynPad.UI.OpenDocumentViewModel.Initialize(DocumentId documentId, Action`1 onError, Func`1 getSelection, IDisposable viewDisposable) in D:\src\gh\aelij\roslynpad\src\RoslynPad.Common.UI\ViewModels\OpenDocumentViewModel.cs:line 615
   at RoslynPad.DocumentView.OnDataContextChanged(Object sender, EventArgs args) in D:\src\gh\aelij\roslynpad\src\RoslynPad.Avalonia\DocumentView.axaml.cs:line 60
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore() in /_/src/Avalonia.Base/Threading/DispatcherOperation.cs:line 392
   at Avalonia.Threading.DispatcherOperation.Execute() in /_/src/Avalonia.Base/Threading/DispatcherOperation.cs:line 262
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job) in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 122
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore() in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 153
   at Avalonia.Threading.Dispatcher.OnOSTimer() in /_/src/Avalonia.Base/Threading/Dispatcher.Timers.cs:line 130
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 162
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl) in /_/src/Avalonia.Base/Threading/DispatcherFrame.cs:line 117
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame) in /_/src/Avalonia.Base/Threading/Dispatcher.MainLoop.cs:line 53
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.MainLoop.cs:line 80
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 127
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 220
   at RoslynPad.Program.Main(String[] args) in D:\src\gh\aelij\roslynpad\src\RoslynPad.Avalonia\Program.cs:line 13
[1]    9108 IOT instruction (core dumped)  dotnet RoslynPad.dll
```

**To Reproduce**
`dotnet RoslynPad.dll`

**Version**
- OS:
```
☁  RoslynPadAvalonia  dotnet --info       
.NET SDK:
 Version:   7.0.113
 Commit:    e24ee34c8e

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  21.2
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/sdk/7.0.113/

Host:
  Version:      7.0.13
  Architecture: x64
  Commit:       3f73a2f186

.NET SDKs installed:
  7.0.113 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.13 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.13 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```
- Build (or commit ID if built from source): Release 18

**Comment by aelij** [comment]
Duplicate of #470

**Comment by catalin560** [comment]
> Duplicate of #470

ok... but how do I fix it?

**Comment by aelij** [comment]
It's already fixed in the main branch. Will be included in the next release.

**Comment by catalin560** [comment]
> It's already fixed in the main branch. Will be included in the next release.

so there is no way to make it work today?

**Comment by tomuxmon** [comment]
It appears `/usr/lib64/dotnet` was added to the `dotnetPaths` but not the '/usr/lib/dotnet' (inside `PlatformsFactory.cs`). So still get the same error using the `main` branch from yesterday. adding `/usr/lib/dotnet` to `dotnetPaths` allows me to launch RoslynPad in debug but not in release (another story :smile:).

**Comment by aelij** [comment]
@tomuxmon Can you please submit a PR to add the path?
